# Generated by Django 3.1.4 on 2023-03-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_sold_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='distributors',
            options={'verbose_name': 'Дистрибутор', 'verbose_name_plural': 'Дистрибутори'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Моите Служители'},
        ),
        migrations.AlterField(
            model_name='sold',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
