# Generated by Django 3.1.4 on 2023-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20230319_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_address', models.URLField(blank=True, null=True)),
                ('company', models.ManyToManyField(to='leads.Company')),
            ],
        ),
    ]
