# Generated by Django 3.1.4 on 2023-03-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20230329_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='marsh',
        ),
        migrations.AddField(
            model_name='sold',
            name='profit_procent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
