# Generated by Django 3.1.4 on 2023-03-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20230329_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
