# Generated by Django 3.1.4 on 2023-03-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20230330_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(to='leads.Company'),
        ),
    ]
