# Generated by Django 3.1.4 on 2023-03-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20230330_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('first_name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенти'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='sold',
            name='we_delivered',
            field=models.BooleanField(default=True),
        ),
    ]
